"""Etapas y pasos de la app, con la numeración y los títulos de estudio_etapas.html."""

ETAPAS = {
    "01": "EDA y preprocesamiento",
    "02": "Clasificación de NObeyesdad",
    "03": "Regresión de Weight",
    "04": "Clustering K-Means",
    "05": "Comparación final",
}

PASOS = {
    "01": [
        ("1", "Carga y EDA mínimo"),
        ("2.1", "Distribución de las 7 clases"),
        ("2.2", "Distribución de Weight"),
        ("2.3", "Chequeo de fuga de datos"),
        ("2.4", "Correlaciones entre numéricas"),
        ("3", "Preprocesamiento → clf.csv y reg.csv"),
    ],
    "02": [
        ("1", "Datos y split"),
        ("2", "Modelos y grillas"),
        ("3", "Variante A (todas las features): tabla de resultados"),
        ("3.1", "Reportes por clase y matrices de confusión (A)"),
        ("3.2", "Importancia de features del RF (A)"),
        ("3.3", "Árbol de GridSearch dibujado (A)"),
        ("3.4", "Tres árboles: completo, podado y muy podado (prepoda)"),
        ("3.6", "Curva del mejor K de KNN (A)"),
        ("3.7", "¿Cuántos árboles necesita el Random Forest?"),
        ("4", "Variante B (sin Weight ni Height)"),
        ("4.1", "Curva del mejor K de KNN (B)"),
        ("5", "Comparación A vs B"),
        ("7", "Robustez ante ruido (jittering) en la variante B"),
        ("8", "Sólo filas reales (sin SMOTE) y sin Weight/Height"),
    ],
    "03": [
        ("1", "Datos y split"),
        ("2", "Modelos, grillas y tabla de resultados"),
        ("2.1", "Curva del mejor K de KNN (regresión)"),
        ("2.2", "¿Cuántos árboles? (regresión)"),
        ("3", "Tres árboles de regresión (prepoda)"),
        ("4", "Predicho vs real (modelos principales)"),
        ("5", "Importancia de features (RF de regresión)"),
        ("6", "Comparación de métricas y R² ajustado"),
    ],
    "04": [
        ("1", "Datos escalados"),
        ("2", "Barrido de K (tabla)"),
        ("2.1", "Método del codo"),
        ("2.2", "Silueta, Calinski-Harabasz y Davies-Bouldin"),
        ("2.3", "Estadístico gap"),
        ("2.4", "¿Coinciden los 5 métodos?"),
        ("3", "K = 7 vs clases reales: métricas"),
        ("3.1", "Tabla de contingencia (clusters × clases)"),
        ("3.2", "Matriz mapeada con el algoritmo húngaro"),
        ("3.3", "Centroides en unidades originales"),
        ("3.4", "PCA 2D: clusters vs clases"),
        ("3.5", "Iteraciones de K-Means"),
        ("4", "Variantes con la columna de clase (ejercicio académico)"),
        ("4.1", "Elección de K con clase ordinal (5 métodos)"),
        ("4.2", "K = 7 con clase: contingencia cruda y matrices mapeadas"),
        ("4.3", "Tabla comparativa sin/con clase"),
        ("4.4", "PCA 2D con clase ordinal"),
        ("5", "Variante sólo numéricas (8 features)"),
    ],
    "05": [
        ("1", "Resultados de todos los casos"),
    ],
}
